removed sdk content from readme
cyberark/cyberark-conjur-cli pull request #401
Opened 2022-01-25 10:28 UTC by mbenita-Cyberark

added link to SDK repo

### Desired Outcome

SDK is now leaving under a different repo.
we should remove it from our docs and add reference to it in the README.md file

### Implemented Changes

- Removed sdk content from readme
- Added link to SDK repo
- Updated changelog

#### Changelog

- [x] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [x] The changes in this PR do not require tests

#### Documentation

- [x] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [ ] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [ ] These changes are part of a larger initiative that will be reviewed later, or
- [x] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [ ] These changes are part of a larger initiative with a separate security review, or
- [x] There are no security aspects to these changes

2022-01-25 11:28 UTC, shulifink requested changes
Good idea!

2022-01-25 11:28 UTC, shulifink commented on CHANGELOG.md
> +- `SDK` with all it contents was removed and now maintained under https://github.com/cyberark/conjur-api-python
```suggestion
- `SDK` with all it contents was removed and is now maintained in the https://github.com/cyberark/conjur-api-python repository
```

2022-01-25 11:28 UTC, shulifink commented on README.md
> +Note: Conjur python SDK was removed from this repo and is now maintained under
```suggestion
Note: The Conjur Python SDK was removed from this repo and is now maintained in the 
```

2022-01-26 09:45 UTC, InbalZilberman reviewed
LGTM

2022-01-26 11:40 UTC, eladkug submitted a review, later dismissed
LGTM

2022-01-26 13:03 UTC, orenbm commented
@mbenita-Cyberark please squash these commits before merging so that we don't have a `merge from main` commit in the git history

2022-02-02 14:03 UTC, orenbm approved these changes

2022-02-03 06:56 UTC, merged